# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='token_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
